#!/usr/bin/env bash

# 🚀 CMS LIFECYCLE IMPLEMENTATION - Quick Setup

echo "================================"
echo "CMS LIFECYCLE SETUP"
echo "================================"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}STEP 1: Run Database Migration${NC}"
echo "This will:"
echo "  - Add soft delete columns to pages"
echo "  - Create themes table"
echo "  - Create templates table"
echo "  - Create page_revisions table"
echo "  - Add performance indexes"
echo ""
echo "Command:"
echo "  cd backend"
echo "  php migrate_cms_lifecycle.php"
echo ""
read -p "Press Enter to continue..."

echo ""
echo -e "${BLUE}STEP 2: Verify Database Changes${NC}"
echo "Check that migration succeeded:"
echo ""
echo "MySQL commands to verify:"
echo "  DESCRIBE pages;  -- Should show new columns"
echo "  SHOW TABLES;     -- Should include: themes, templates, page_revisions"
echo ""

echo ""
echo -e "${BLUE}STEP 3: Update Frontend Router${NC}"
echo "Add this route to your PublicLayout or main router:"
echo ""
echo "Code example (src/app/routes.tsx):"
echo "  import PublicPageRenderer from './components/PublicPageRenderer';"
echo ""
echo "  const routes = ["
echo "    {"
echo "      path: '/:slug',"
echo "      element: <PublicPageRenderer websiteId={websiteId} slug={slug} />"
echo "    }"
echo "  ]"
echo ""

echo ""
echo -e "${BLUE}STEP 4: Test the Complete Flow${NC}"
echo ""
echo "In Admin Panel:"
echo "  1. Create a page:"
echo "     Title: 'Test Page'"
echo "     Slug: 'test-page'"
echo "     Status: 'draft'"
echo ""
echo "  2. Publish it:"
echo "     Edit page → Status: 'published' → Save"
echo ""
echo "  3. Visit public site:"
echo "     http://localhost:5173/test-page"
echo "     Should display with theme layout"
echo ""
echo "  4. Delete it (soft delete):"
echo "     Click Delete → Confirms soft delete"
echo ""
echo "  5. Visit again:"
echo "     http://localhost:5173/test-page"
echo "     Should show 404 (page hidden)"
echo ""
echo "  6. Restore it:"
echo "     Go to deleted pages → Restore"
echo "     Status changes to 'draft'"
echo ""

echo ""
echo -e "${GREEN}✅ SETUP COMPLETE!${NC}"
echo ""
echo "Your CMS now has:"
echo "  ✅ Soft delete system (data preserved, not visible)"
echo "  ✅ Theme/layout system (automatic page rendering)"
echo "  ✅ Menu filtering (published pages only)"
echo "  ✅ Complete page lifecycle (draft → published → deleted)"
echo "  ✅ SEO metadata support"
echo "  ✅ Version history tracking"
echo ""
echo "📖 Read CMS_LIFECYCLE_ARCHITECTURE.md for complete docs"
echo ""
